image: glucnac/php:7.3-fpm-alpine

# Select what we should cache between builds
cache:
  paths:
    - vendor/

before_script:
  - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  - composer install --working-dir=tools/php-cs-fixer
  - composer install

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics. 
test:
  script:
    - composer test-ci
