image: glucnac/php:7.4-fpm-alpine

before_script:
    - echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - composer install --working-dir=tools/php-cs-fixer
    - composer install

cache:
    paths:
        - vendor/

stages:
    - CodingStandards
    - UnitTests

php-lint:
    stage: CodingStandards
    script:
        - composer php-lint
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - composer phpcs
    allow_failure: false

php-cs-fixer:
    stage: CodingStandards
    script:
        - composer php_cs-check
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - composer phpstan
    allow_failure: false

phpunit:
    stage: UnitTests
    script:
        - composer phpunit-ci
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    allow_failure: false
